version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 5
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
      day: monday
      time: "03:15"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 5
    groups:
      cargo-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 5
